on: push

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: ./build.ps1
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: Build/Publish/*.vsix
      - uses: actions/upload-artifact@v4
        with:
          name: Build artifacts
          path: Build/Publish/*.vsix
